
title: ironstone@github
url: 'https://mustafatasdemir.github.io'
baseurl: '/' #change it according to your repository name


#Profile information
name: Mustafa Ta≈üdemir
tagline: Software Engineer
pic: profile.png

#sidebar links
email: mustafa.tasdemir@hotmail.com.tr
website: mustafatasdemir.net #do not add http://
linkedin: mustafatasdemir
github: mustafatasdemir
location: Sunnyvale, CA
